### PR TITLE
#599 Fixed horizontal autoscrolling issue

### LINKED ISSUE #599: [BUG]: No Horizontal Scroll if the text overflows the text box
### Description

I uploaded a new python snippet the snippet goes as follows 
```python
@pytest.mark.asyncio⏎
@pytest.mark.parametrize("username, password", username_password_list)⏎
async def test_all_details(username, password):⏎
    async with aiohttp.ClientSession() as sess:⏎
        user_name = await generate_session(username, password, sess)⏎
        if user_name is None:⏎
            assert False, "Login Failed!"⏎
        all_details = await get_all_details(sess, user_name)⏎
⏎
        for k, v in all_details.items():⏎
            assert v is not None or len(v) == 0 , f"Failed to get {k}"
```

I have a relatively small laptop display and what happened is that when i was typing the horizontal scroll didn't work.
What can we do to fix this problem: 
- turn auto wrap on for the text box. 
- make it auto scroll if the text isn't visible and we are typing it.

### (optional) What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Aadeshcode**
---
title: Issue #599 | Fixed horizontal autoscrolling issue if the text overflows
---

## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [ ] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description

Solved the horizontal autoscrolling problem if the text overflowed in the race-practice page. Both left and right scrolls are working and line breaks are working as well. User will also be rescrolled to current cursor position on typing even if manually scrolled to another scroll position

## Related Tickets & Documents

- Related Issue #599
- Closes #599 

## QA Instructions, Screenshots, Recordings

https://github.com/webdevcody/code-racer/assets/66826040/1b654ee7-d0c1-4e23-937a-630b28b7d348

## Added/updated tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

### CODE REVIEW

File: packages/app/src/app/race/_components/race/race-practice.tsx [hunk 1]
```diff
@@ -32,20 +33,39 @@ export default function RacePractice({ user, snippet }: RacePracticeProps) {
...
   const router = useRouter();
   const isRaceFinished = input === code;
 
   const isUserOnAndroid = useCheckForUserNavigator("android");
-
+  //for auto scroll
+  const preElement = useRef<HTMLPreElement | null>(null);
+  const scrollUpperLimit = 7;
+  const scrollLowerLimit = 7 - 1; //1 is deducted because when scrolling backwards, we count from the left side
+  const spanElementWidth = 10.4; //the span element will always have this width
```
Comment (scape76) [inline packages/app/src/app/race/_components/race/race-practice.tsx:49]: what about the span element with ⏎ symbol? It has a width of 14.4

Comment (Aadeshcode) [reply packages/app/src/app/race/_components/race/race-practice.tsx:49]: We need not worry about that. When the user reaches ⏎, we scroll to (0,0).

Comment (scape76) [reply packages/app/src/app/race/_components/race/race-practice.tsx:49]: oh, okay, well done
